export default {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  TOGGLE_TODO_COMPLETED: "TOGGLE_TODO_COMPLETED",
  FILTER_TODO: "FILTER_TODO",
  FILTER_BY_TYPE: "FILTER_BY_TYPE",
  CLEAR_FILTER: "CLEAR_FILTER",
};
